version: "3.1"
services:
  dev:
    container_name: universities-dev
    build:
      context: .
      target: development
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - .:/home/app
      - /home/app/node_modules
  
  prod:
    container_name: universities-prod
    build:
      context: .
      target: production
    env_file: 
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: always